export const REQUEST_SALES_ACCOUNTS = 'REQUEST_SALES_ACCOUNTS';
export const RECEIVE_SALES_ACCOUNTS = 'RECEIVE_SALES_ACCOUNTS';
export const CLEAR_SALES_ACCOUNT_SEARCH = 'CLEAR_SALES_ACCOUNT_SEARCH';

export const REQUEST_SALES_ACCOUNT = 'REQUEST_SALES_ACCOUNT';
export const RECEIVE_SALES_ACCOUNT = 'RECEIVE_SALES_ACCOUNT';

export const REQUEST_DISCOUNT_SCHEMES = 'REQUEST_DISCOUNT_SCHEMES';
export const RECEIVE_DISCOUNT_SCHEMES = 'RECEIVE_DISCOUNT_SCHEMES';

export const REQUEST_TURNOVER_BAND_SETS = 'REQUEST_TURNOVER_BAND_SETS';
export const RECEIVE_TURNOVER_BAND_SETS = 'RECEIVE_TURNOVER_BAND_SETS';

export const SHOW_EDIT_MODAL = 'SHOW_EDIT_MODAL';
export const HIDE_EDIT_MODAL = 'HIDE_EDIT_MODAL';