export const REQUEST_SALES_ACCOUNTS = 'REQUEST_SALES_ACCOUNTS';
export const RECEIVE_SALES_ACCOUNTS = 'RECEIVE_SALES_ACCOUNTS';
export const CLEAR_SALES_ACCOUNT_SEARCH = 'CLEAR_SALES_ACCOUNT_SEARCH';

export const REQUEST_SALES_ACCOUNT = 'REQUEST_SALES_ACCOUNT';
export const RECEIVE_SALES_ACCOUNT = 'RECEIVE_SALES_ACCOUNT';
